[database]
host = localhost
db = metrics
port = 3306


[sites]
ignored_sites = TRL1
mislabelled_sites = NWTP,LPWR,CPVN,HBSR


[thresholds]
; Threshold where regular sites will be considered good
regular_threshold = 300

[specialsites]
; Site to threshold mapping: site will be considered "good" if above the given threshold here
FLND = 200
STLI = 200
VIEW = 200
SUNS = 200
SEA1 = 200
PORT = 200
SLID = 200
OLDB = 50
RDSR = 50
NAPL = 50
VENI = 50