<?php

/**
 * Convert a hex string (e.g. 'FF0000') to an integer (e.g. 16711680).
 */
function colormap_hex2int($hex) {
    // Strip any leading # or 0x
    $hex = ltrim($hex, '#');
    $hex = str_ireplace('0x', '', $hex);
  
    // Validate
    if (!ctype_xdigit($hex)) {
        return false;
    }
  
    // Convert
    return hexdec($hex);
  }

  function colormap_int2rgb($val) {
    $r = ($val >> 16) & 0xFF;
    $g = ($val >> 8)  & 0xFF;
    $b = $val & 0xFF;
    return [$r, $g, $b];
  }
  
  /**
  * Convert a 24-bit integer (or 32-bit if alpha was packed) to RGBA array.
  * 
  * For simplicity, we assume there's no separate alpha in the top bits, so
  * alpha=0 (fully opaque). If you do store alpha in the top bits, you can 
  * adjust the code accordingly.
  */
  function colormap_int2rgba($val) {
    // Extract R, G, B (lowest 24 bits)
    $r = ($val >> 16) & 0xFF;
    $g = ($val >> 8)  & 0xFF;
    $b = $val & 0xFF;
  
    // Default alpha channel is 0 (fully opaque)
    $a = 0; 
  
    return array($r, $g, $b, $a);
  }
  
  /**
   * Generate a color map gradient based on a specified ramp schema.
   *
   * Available ramp schemas:
   *   4 => [blue, green, orange, red]
   *   3 => [blue, pink]
   *
   * The gradient is generated by evenly interpolating between the colors.
   *
   * @param int $steps  The number of color steps to generate.
   * @param int $scheme The ramp schema to use.
   * @return array An array of RGB colors.
   */
  function colormap_generate($steps, $scheme = 4) {
    // Define ramp schemas: each schema is an array of [R, G, B] colors.
    $rampSchemas = [
        4 => [
            [1, 35, 125],    // blue
            [100, 180, 30],    // green
            [190, 80, 0],  // orange
            [130, 0, 0]     // red
        ],
        3 => [
            [64, 224, 208],  // teal
            [128, 128, 192], // a mid purple tone 
            [255,   0, 255]  // magenta/pink
        ],
        2 => [
            [0,   0,   255],  // blue
            [0,   255, 0],    // green
            [255, 165, 0],    // orange
            [255, 0,   0]     // red
        ],
        1 => [
            [255, 255, 255],  // white
            [255, 255,   0],  // yellow
            [255, 165,   0],  // orange
            [180,  90,   0],   // deeper orange/brown tone
            [130, 0, 0] 
        ],
        0 => [
            [0,   0, 128],  // Deep Blue
            [0,   0, 255],  // Blue
            [0,  255, 255], // Cyan
            [255, 255,   0],// Yellow
            [255,   0,   0],// Red
            [128,   0,   0] // Deep Red
        ]
    ];
  
    // Use the specified scheme or fall back to the default if not defined.
    if (!isset($rampSchemas[$scheme])) {
        $colors = $rampSchemas[4];
    } else {
        $colors = $rampSchemas[$scheme];
    }
  
    $numSegments = count($colors) - 1;
    $map = [];
  
    // Generate the gradient by mapping each step to a position along the overall gradient.
    for ($i = 0; $i < $steps; $i++) {
        // Normalize t from 0 to 1 across the total number of steps.
        $t_global = $steps > 1 ? $i / ($steps - 1) : 0;
  
        // Determine which segment of the color ramp we are in.
        $segment = min(floor($t_global * $numSegments), $numSegments - 1);
        // Calculate the local interpolation value for this segment.
        $t_local = ($t_global - ($segment / $numSegments)) * $numSegments;
  
        // Get the starting and ending colors for this segment.
        $startColor = $colors[$segment];
        $endColor = $colors[$segment + 1];
  
        // Interpolate each RGB channel.
        $r = round($startColor[0] + ($endColor[0] - $startColor[0]) * $t_local);
        $g = round($startColor[1] + ($endColor[1] - $startColor[1]) * $t_local);
        $b = round($startColor[2] + ($endColor[2] - $startColor[2]) * $t_local);
  
        $map[$i] = [$r, $g, $b];
    }
  
    return $map;
  }

?>