services:
  hfrnet-mysql:
    image: mysql:8.0
    container_name: hfrnet-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ../.env
    volumes:
      - hfrnet_mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - hfrnet

networks:
  hfrnet:
    external: true

volumes:
  hfrnet_mysql_data:
    driver: local