[debug]
# NOTE: enabling profiling will disable request cancellation, as a
#       suitable workaround for handling disconnection has not been
#       found when using the HTTP profiling middleware.
#       See https://github.com/Kludex/starlette/discussions/2094
profiling = false

[data_database]
host = localhost
user =
passwd =
db = hfradar
port = 3306

[errors]
email =

[directories]
; s3 rootdir to be used for total velocity requests
rootdir = /hfrtv

[urls]
valid_res = 1km,2km,6km,500m
valid_pfx = h,a,am,ma,ay,ya

default_prod = a_6km

default_lat1 = 73
default_lat2 = 13
default_lon1 = -170
default_lon2 = -49

; default request time if none is provided (15 hours in seconds)
default_time_offset = 54000


default_out = json
default_callback = eqfeed_callback

[usregions]
; bounding boxes for the US regions
AKNS = 68,-174,74,-128
GAK = 50,-167,62,-123
GLNA = 41,-92,50,-76
USWC = 30,-130,50,-115
USEGC = 21,-97,47,-57
USHI = 16,-163,25,-151
PRVI = 14,-70,22,-61

[latest]
; regions that are excluded from being checked for data in the /latest endpoint (useful for excluding offline regions)
exclude_regions = AKNS,GAK

[waves]
; -6 days in seconds
default_history_t0 = 518400
